### ISSUE TITLE
Delegate Pattern

### ISSUE THREAD

**Issue by Glsme** [NOW-ON/iOS-Interview-Preparation#10]
### 🗓️ 마감일 
2023.01.22

### 💁 참여자

- [x] 김도이
- [x] 윤여진
- [x] 홍석준
- [x] 이주영
- [x] 이재용

⚠️ 마지막으로 답변 단 사람이 이슈 close 하고 리드미에 항목 업데이트 해주세요.

**Comment by Yun-YeoJin** [comment]
- 이벤트를 받은 객체와 그 이벤트를 처리할 객체가 다른 경우, 두 객체를 연결하기 위해 Delegate 패턴을 사용한다.
- 즉 두 개의 객체가 효율적으로, 필요할 때 연결되도록 해주는 것이다.
- 이벤트를 받는 객체가 그 이벤트를 받아 어떤 행동을 할지 위임해주는 것이다.

```swift
//값을 보낼 SearchViewController
final class SearchViewController: BaseViewController {

lazy var delegate: SendStockDelegate?

func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let stockNameData = stockList[indexPath.row].stockName
        delegate?.sendStockName(stockNameData)
        self.dismiss(animated: true)
    }

//값을 받을 BuyandSellViewController
public protocol SendStockDelegate: AnyObject {
    func sendStockName(_ text: String)
}

final class BuyandSellViewController: BaseViewController, SendStockDelegate {
    func sendStockName(_ text: String) {
        mainView.contentSearchBar.text = text
    }
}
```

**Comment by LeeJoobang** [comment]
- 하나의 객체는 다른 객체를 자신의 대리자로 지정한다. 그리고 자신이 제공하는 일부 기능을 대리자가 대신 수행하도록 일부 위임한다. 기능을 처리할 객체를 델리게이트로 설정하고, 특정 이벤트가 발생할 때 이를 델리게이트에 의해 위임된 본래의 객체로 전달해주는 역할을 한다.
- 대표적인 예는 테이블뷰, 텍스트 필드
- 테이블 항목을 선택했을 때 - 실행해야 하는 기능이 다양할텐데, 테이블뷰 뷰는 어떤 기능을 실행해야 하는지 모른다. 이 부분을 대대리자가 대신 처리하도록 위임한다.
- 델리게이트 패턴 사이에 두개의 객체가 존재하낟. 기능을 위임하는 테이블뷰, 테이블 뷰의 기능을 대신 수행하는 delegate object
- delegate 객체는 테이블뷰가 호출하는 메소드를 구현한다.
- 특정시점에 호출되는 메소드는 프로토콜로 선언되어 있다.
- ios에서 델리게이트 패턴을 사용하는 모든 객체는 델리게이트 메소드를 정의한 프로토콜을 가진다. 델리게이트 메소드를 이용하면 델리게이트 프로토콜을 구현하는 과정이 반드시 필요하다.
- 역할, 데이터를 공급하고 이벤트를 처리한다. 왜 사용하는가? 개발 유연성이 증가한다.

**Comment by heydoy** [comment]
##  Delegation
프로토콜을 정의하여 구현함으로써 위임이 된 책임을 캡슐화하며, 준수한 유형(Delegate=대리자)이 위임된 기능을 제공하도록 보장한다. Delegation은 특정 액션에 반응하도록 하거나, 소스의 기본타입을 알지 못 해도 외부에 있는 소스의 데이터를 검색하는 등에 사용된다. 

* 참고링크: https://docs.swift.org/swift-book/LanguageGuide/Protocols.html#ID276 

### 목적
Delegate 패턴의 핵심적인 목표는 객체가 분리된 방식으로 객체 소유자와  통신할 수 있게 하는 것이다. 객체가 소유자의 구체적인 유형을 알지 않도록 함으로써, 개발자가 재사용 및 유지보수가 더 쉬운 코드를 작성할 수 있게 한다. 

* 참고링크: https://www.swiftbysundell.com/articles/delegation-in-swift/

## 예시코드
```swift
// 이 프로토콜은 고양이가 집사에게 지시할 모든 것을 가지고 있음 
protocol CatDelegate {
    func feedCat(for cat: Cat, food: CatFood) -> CatFood
    func howMuchTimeWePlayed(for cat: Cat, toy: Toy) -> Int
    func isSandPreferable() -> Bool
}

class Cat {
    // 고양이는 집사가 무슨 클래스이든 상관없음 
    // 단지 집사가 고양이를 위해 해야되는 일을 할 수 있어야함.
    weak var jipsa: CatDelegate? 

    // 집사가 일을 하는 평일과  whenever the manager needs those tasks done, they just have the assistant do it
    func performTasks {
      switch today {
         case .weekday: 
              catFood = jipsa.feedCat(for: self, catFood: Tuna) 
              playTime = jipsa.howMuchTimeWePlayed(for: self, toy: KashaKasha) 
         case .weekend:
             isSandPreferable = jipsa.isSandPreferable()
     }
}
// 집사는 프로토콜을 채택해야한다. 프로토콜의 요구사항을 모두 만족해야 컴파일이 된다. 
class Jipsa: CatDelegate {
    func feedCat(for cat: Cat, food: CatFood) -> CatFood {
       // 고양이에게 밥을 주는 코드 
       return food 
    }
    func howMuchTimeWePlayed(for cat: Cat, toy: Toy) -> Int {
      // 고양이와 장난감으로 놀아주기  
      return time
   }
    func isSandPreferable() -> Bool  {
       // 고양이 모래 선호도 분석하기
      return true
    }
}

```

##  왜 Delegate Pattern을 쓸까?
1. 적절하게 관심사를 분리할 수 있도록 함 -> 클래스 간 결합도를 낮춤 (decoupling)
ㄴ 예를 들어, 고양이는 고양이에 대한 논리만 가질 수 있고, 고양이를 지원해야되는 일에 대해서 클래스에 정의하지 않아도 된다.
2. 재사용성

* 참고링크: https://dilloncodes.com/delegate-pattern-in-swift

**Comment by Glsme** [comment]
# Delegate
**디자인 패턴으로 클래스나 구조체의 책임 중 일부분을 다른 타입의 인스턴스에게 전달(위임)하는 역할을 하는 것입니다.**

<br/></br>
## Delegate Pattern
**위임자를 갖고 있는 객체가 다른 객체에게 자신의 일을 위임하는 형태의 디자인 패턴이다.**

### Delegate Pattern 동작 방식
1. Delegate Protocol을 선언한다.
2. 일을 전달하는 ViewController 내 프로퍼티에 Delegate를 저장한다.
3. 일을 전달받을 ViewController에서 전달하는 ViewController 내 Delegate를 저장한 프로퍼티를 자신으로 위임자로 삼는다.
4. 일을 전달받을 ViewController에서 일을 처리한다.

<br/></br>
## Delegate Pattern을 사용하면 retain되는 이유
Delegate Pattern을 사용하면 두개의 클래스가 서로 참조하는 상황이 필연적으로 발생한다.
이 때 일을 전달받을 ViewController에서 Delegate를 처리 후 일을 전달하는 ViewController는 이미 deinit이 되었기 때문에 일을 전달받은 입장에선 메모리를 해제할 수 없다.
따라서 메모리를 정상적으로 해제하려면 `weak`키워드를 붙여 MemoryLeak이 발생하지 않도록 해주어야한다.

**Comment by wodyddml2** [comment]
## Delegate Pattern
위임자(Delegate)를 갖고 있는 객체가 다른 객체에게 자신의 일을 위임하는 형태의 디자인 패턴

- 위임자는 프로토콜 타입으로 생성
- 객체 사이의 이벤트를 처리하기 위해 주로 사용
- 즉, Delegate는 어떤 객체가 해야 하는 일을 부분적으로 확장해서 대신 처리하는 역할

## Delegate Pattern 사용 시 주의할 점
객체끼리 연결하면서 강한 참조 순환이 발생하기 때문에 weak 키워드를 사용해 메모리 릭을 방지해야한다.
