### ISSUE TITLE
Closure & Escaping Closure

### ISSUE THREAD

**Issue by Glsme** [NOW-ON/iOS-Interview-Preparation#11]
### 🗓️ 마감일 
2023.01.22

### 💁 참여자

- [x] 김도이
- [x] 윤여진
- [x] 홍석준
- [x] 이주영
- [x] 이재용

⚠️ 마지막으로 답변 단 사람이 이슈 close 하고 리드미에 항목 업데이트 해주세요.

**Comment by Yun-YeoJin** [comment]
### **1. 클로저(Closure)** 
- 사용자 코드 안에서 전달되어 사용할 수 있는 로직을 가진 { }로 구분된 코드 블럭
- 따로 function을 만들어야 할 불편함 없이 즉석에서 만들 수 있음.
- 후행 클로저(trailing Closure)를 이용해 마지막 매개변수 이름을 생략하고 { }로 사용할 수 있음.
- 타입 생략 가능, return 값이 한 줄일때 return 생략 가능, 매개변수 생략 가능($0, $1)
- 기본적으로 함수의 인자로 들어오는 Closure는 함수 내부에서만 사용 가능. 함수 외부에 저장 및 다른 스레드에서 해당 클로저를 실행 불가 ❌

### **2. 탈출 클로저(Escaping Closure)**
- 클로저 타입 앞에 `@escaping` 를 붙이면 탈출 클로저로 바꿀 수 있고, 탈출 클로저는 해당 함수가 반환된 후 실행되므로, 일반적인 클로저와 달리 **함수 외부에 저장하거나 다른 스레드에서 실행 가능** 🟢
- **깔끔한 아키텍처 설계**에도 도움이 됨!!!
- 탈출 클로저는 해당 함수가 반환된 후 실행되기 때문에 **함수 간 실행 순서**도 고려할 수 있다.

**Comment by LeeJoobang** [comment]
- 먼저 클로져는 왜 쓰는 것일까?  비동기 작업에서 많이 사용되고 있다. 비동기적인 어떤 테스크가 끝나고 나서 수행해야 할 블록을 클로져로 작성하면 편리하다. 클로져는 비동기 작업에서 많이 사용되는데, 클로저를 통해 비동기 콜백을 작성하는 경우 현재 상태를 미리 획득해 놓지 않으면 실제로 클로져의 기능을 실행하는 순간, 상수나 변수가 이미 메모리에 존재하지 않는 경우가 발생할 수 있다. 이때 필요한 것이 바로 클로져의 값 캡쳐 기능이다.
  - 값 캡쳐는 말 그대로 캡쳐해서 사용하는 것을 말한다. 값을 캡쳐해서 가지고 있다가. 필요할 때마다 이용하는 것이다. 
  - 리턴 타입의 함수객체를 선언했을 때, 주석을 확인하면 선언할 때마다 결과값이 증가된다.
  - total 변수가 캡쳐되어 새롭게 선언될때마다 초기화하지 않고, 그전에 캡쳐된 값으로 계속해서 사용한다는 것을 의미한다.
  - 이렇게 값 캡쳐를 통하면 add 함수는 언제 호출되더라도 자신만의 total 변수를 가지고 카운트하게 된다. total 참조를 획득했기 때문이다.
  - **값 캡쳐는 값을 미리 획득, 선언될 때마다 획득한 값의 참조에 연산을 누적하는 것이다.**
  - 클로져에서 값을 캡쳐한다는 것은 - 내부함수와 내부함수에 영향을 미치는 주변 환경을 모두 포함한 객체이다. 
- 클로져란 익명함수는 클로져 내부에서 외부변수인 num이라는 변수를 사용하고 있다. num의 값을 클로져 내부적으로 저장하고 있는데, 이것은 클로져에 의해 num의 값이 캡쳐 되었다 라고 표현함.
  - message란 변수는 클로져 내부에서 사용하지 않기 때문에 클로져에 의해 값이 캡쳐 되지 않음.
- 클로져의 값 캡쳐 방식 - 클로져는 값을 캡쳐할 때, value / reference 타입에 관계없이 reference capture한다. 변수를 클로져 내부적으로 저장한다고 했음. 클로져는 value / reference 타입에 관계없이 캡쳐하는 값들을 참조함. reference capture라고 함.
  - 클로져는 임의의 외부변수를 클로져 내부에서 사용하기 때문에 임의의 외부변수를 캡쳐함. 임의의 외부변수를 참조한다.
  - 그런데 value type으로 캡쳐를 하고 싶으면 어떻게 할까? 
  - 이때 캡쳐 리스트를 사용한다.  - 캡쳐리스트는 결국 기본적으로 reference type으로 캡쳐된 내용을 value type으로 캡쳐하고 싶을 때 사용하는 것이다. 어떻게 하냐면 value type의 경우 value capture하고 싶은 변수를 리스트로 명시해주는 것이다.



- 탈출 클로져? 함수의 인자로 전달된 클로져가 함수가 반환된 후 실행되는 클로져를 의미한다. 전달 받은 클로져가 클로져 함수 외부로 다시 반환되거나 외부 글로벌 변수에 저장되는 경우 이경우 @escaping을 붙여줘야 하고, 그렇지 않으면 complie 한다.
  - 먼저 클로져는 2가지 종류가 있다.
  - non-escaping closure, escaping closure가 있다.
  - non-escaping closure는 클로져가 함수가 종료되기 전에 실행되는 것
  - escaping closure는 함수 실행 중 즉시 실행되지 않고, url 요청이 끝난 후 비동기로 실행된다. 
  - 클로져가 다른 변수에 저장되거나 나중에 실행되거나 비동기로 실행될 때 escaping 클로져가 사용된다.

**Comment by heydoy** [comment]
## Closure
클로저는 코드에서 사용되며, 다양하게 전달될 수 있는 독립적인 기능 블록. 
Swift의 클로저는 오브젝티브 C와 C의 블록, 다른 프로그래밍 언어의 람다와 유사.

클로저는 클로저가 정의된 맥락에서 상수와 변수의 참조를 저장하고 캡쳐할 수 있다. 

## 클로저 표현식
```swift
{ (parameters) -> return type in
    statements
}
```

## 클로저는 참조 타입
함수와 클로저는 참조 타입
클로저를 서로 다른 상수, 변수에 할당하면 동일한 클로저를 참조하고 참조 카운트가 증가. 



## Escaping Closure
탈출 클로저는 함수에 대한 인수로 전달되나, 함수가 반환된 이후에 호출된다. `@escaping` 키워드를 클로저 앞에 적어 사용한다.
```swift
let completionHandler = () -> Void 
func havingEscapingClosure(completionHandler: @escaping () -> Void) {
    completionHandlers.append(completionHandler)
}
```

* 참고링크: https://docs.swift.org/swift-book/LanguageGuide/Closures.html

**Comment by Glsme** [comment]
## Closure
- 클로저는 Named Clousre & Unnamed Closure 둘다 포함하지만, 보통 Unnamed Closure를 말한다.
- 클로저는 함수이기 때문에 일급 객체 함수의 특성을 가진다.
<br/></br>
### 1급 객체로서 클로저 특징
- 클로저를 변수나 상수에 대입할 수 있다.
```swift
let closure = { () -> () in
    print("Closure")
}
```
- 함수의 파라미터 타입으로 클로저를 전달할 수 있다.

```swift
func doSomething(closure: () -> ()) {
    closure()
}
```

- 함수의 반환 타입으로 클로저를 사용할 수 있다.
```swift
func doSomething() -> () -> () {
}
```
<br/></br>
## 탈출 클로저 (Escaping Closure)
**함수 인자로 클로저가 전달되지만, 함수가 반환된 이후에 실행되는 클로저이다.**
- 탈출 클로저를 사용하기 위해선 앞에 `@escaping` 키워드를 붙여야 한다.
- 보통 비동기 작업을 하기 위해 사용한다.
- 일반 클로저처럼 캡처 현상을 가지고 있어, Memory Leak에 주의하며 사용해야 한다.

**Comment by wodyddml2** [comment]
## Closure
Closure는 익명 함수이며 함수이기에 1급 객체 특성을 가지고 있다.

- 1급 객체
    - 변수에 함수 대입 가능
    - 함수를 반환 가능
    - 인자로 함수를 전달 가능

반환 타입을 생략할 수 있으며 단축 인자 이름을 사용하여 Closure 코드 방식을 줄일 수 있다.

## Escaping Closure

전달인자로 받은 클로저가 매서드 실행이 종료된 후에 호출되는 경우, 탈출 클로저라고 함.

- 대부분의 경우(클로저를 프로퍼티에 저장하거나, 다른 클로저로 전달하는 경우) 메모리 릭을 방지하기 위해 weak self 를 사용해야 한다.
- escaping closure가 아닐 경우 대부분의 경우 weak self 를 사용할 필요가 없다
  - GCD, UIView.Animate 의 클로져는 weak self를 쓸 필요가 없다
