### ISSUE TITLE
Optional & Optional의 내부 구조

### ISSUE THREAD

**Issue by Glsme** [NOW-ON/iOS-Interview-Preparation#12]
### 🗓️ 마감일 
2023.01.22

### 💁 참여자

- [x] 김도이
- [x] 윤여진
- [x] 홍석준
- [x] 이주영
- [x] 이재용

⚠️ 마지막으로 답변 단 사람이 이슈 close 하고 리드미에 항목 업데이트 해주세요.

**Comment by LeeJoobang** [comment]
Optional: 값이 있는 경우와 없는 경우 모두 포함하는 타입

- nil: nil은 값이 없음을 의미함. 상수나 변수에 일반적인 값으로 할당하는 것이 불가하다.(변수 또는 상수에 담으려면 값이 없을 가능성을 내포하고 있어야 함. 결국 변수, 상수에 값을 담을 때 그 값이 어느 시점에 존재하지 않을 수 있어야 한다는 것을 뜻한다. 이에 optional type을 부여함으로써 존재하지 않을 시점에 대해 고려할 수 있게 된다.)

Optional type의 내부구조
- Enum타입으로 이뤄져 있음.
 - 값이 없는 경우(nil)
 - 값이 있는 경우(연관값 - 튜플을 통해 각 case들이 다른 타입을 가지게 할 수 있으며, 또는 여러개의 값을 가질 수 있도록 함.)

**Comment by Yun-YeoJin** [comment]
### Optional 뜻
- “nil”일 수도 있는 값을 들고 있는 타입
- **‘값이 존재하지 않을수도 있음’이라는 의미가 필요할 때 Optional 타입을 사용!**
- !를 사용한 강제 언래핑 방법과, nil 병합 연산자(??)를 이용해서 언래핑 해준다.

### Optional 내부 구조
- Enum으로 이루어져 있음.
```swift
enum Optional<Wrapped> {
    case some(Any)
    case none
}
```
- Case none - 값이 없는 경우 (nil 값)
- Case some - 값이 있는 경우 (연관값)

**Comment by heydoy** [comment]
## Optional 
```swift
@frozen enum Optional<Wrapped>
```
래핑된 값 또는 값이 없음을 뜻하는 `nil` 을 표현하는 타입 


## Optional 사용하기

```swift
let shortOptionalInt: Int? = Int("3")
let longOptionalInt: Optional<Int> = Int("3")
```
옵셔널 타입은 `nil`리터럴 에 해당하는 `.none` 타입과 래핑된 값을 저장하는 `some(Wrapped)`타입, 두가지 케이스로 이루어져 있다.

```swift
let catHere: String? = Optional.some("고양이")
let noneCat: String? = Optional.none
```
옵셔널  값을 사용하려면 값을 언래핑 해야한다. 

##  Unwrapping Optional

### Optional Binding
새 변수에 옵셔널 객체의 래핑된 값을 조건적으로 bind 한다. ` if let`, `guard let`, `switch` 가 있다.
```swift
if let starHere = UIImage(named: "star") {
    print("이미지가 있음")
} else {
    print("이미지를 찾을 수 없음")
}
```

### Optional Chaining
래핑된 개체의 프로퍼티와 메서드를 안전하게 접근하는 방법. 개체에 접미사로 `?`를 붙이고 접근한다. 

```swift
if cat?.isFull("catFood") == true {
    print("고양이가 배부르다")
}
```

### Nil-Coalescing Operator
nil 병합 연산자 `??`을 사용하여 옵셔널 객체가 nil일 경우 기본값을 제공한다. 

```swift
let catFood = stock["catFood"] ?? "없음"
print(catFood)
```
`??` 연산자는 다른 옵셔널 인스턴스를 오른쪽에 붙이는 식으로 여러개의 연산자를 체이닝하여 사용할 수 있다.

```swift
let catFood = stock["catFood"] ?? refrigerator["catFood"] ?? "진짜 없음"
print(catFood)
```

### Unconditional Unwrapping 강제 언래핑 
옵셔널 객체가 값을 가지고 있는 게 확실하다면 강제 해제 연산자 `!`을 이용하여 언래핑할 수 있다. 

```swift
let catFoodCount = Int("30")!
print(catFoodCount)
```
옵셔널 체이닝 때도 강제 해제 연산자 `!`를 이용할 수 있다.

```swift
let hasChurr = cupboard.hasCatFood("츄르")
print(hasChurr)

```
nil 객체를 강제 해제할 경우 런타임 에러가 발생한다. 


* 참고링크: https://developer.apple.com/documentation/swift/optional

**Comment by Glsme** [comment]
### nil을 사용할 수 있는 타입과, 사용할 수 없는 타입을 구분하기 위하여 사용하는 열거형.

### nil 이란?

- **값이 없음을 필요하는 키워드**

```swift
enum Optional<Wrapped> {
	case some(Any)
	case none
}
```
<br/></br>
### 옵셔널값을 추출하는 방법
1. **강제 추출 연산자를 붙여 강제로 옵셔널값을 추출**
```swift
let name: String? = "hano"

print(name!)
```
2. **if문으로 `nil`이 아님을 확인 후, 강제로 추출**
```swift
let name: String? = "hano"

if name != nil {
    print(name!)
}
```
3. **Optional Binding**
- 바인딩(상수나 변수에 대입)이 되는 경우만 특정 작업을 진행.
```swift
if let n = name {
	print(n)
}

func doSomething(name: String?) { // func에서만 사용가능
	guard let n = name else { return }
	print(n)
}
```
4. **Nil-Coalescing**
```swift
print(name ?? "신원미상")
```

5. **Optional Chaining**
- 표현식 자체가 옵셔널의 가능성이 있다는 것을 표현. 
- 체이닝의 결과는 항상 옵셔널이다.
```swift
korea?.seoul?.jungGu
```

**Comment by wodyddml2** [comment]
## Optional
nil을 사용할 수 있는 타입과, 사용할 수 없는 타입을 구분하기 위하여 사용하는 열거형

## Optional 내부 구조
enum 타입으로 이루어져 있음
- 값이 존재하는 some
- 값이 존재하지 않는 none

Optional.none의 케이스로 값이 만들어진 것이 nil

## Unwrapping Optional
- 강제 해제 ( 객체의 값이 nil일 경우 런타임 에러 발생)
- 옵셔널 바인딩
- 옵셔널 체이닝
- 닐 병합 연산 (Nil-Coalescing)
