### ISSUE TITLE
MVVM과 MVC의 차이

### ISSUE THREAD

**Issue by Glsme** [NOW-ON/iOS-Interview-Preparation#13]
### 🗓️ 마감일 
2023.01.29

### 💁 참여자

- [x] 김도이
- [x] 윤여진
- [x] 홍석준
- [x] 이주영
- [x] 이재용

⚠️ 마지막으로 답변 단 사람이 이슈 close 하고 리드미에 항목 업데이트 해주세요.

**Comment by Yun-YeoJin** [comment]
- MVC : Model & ViewController
    - VC에서 모든 비즈니스적 로직과 View를 모두 그린다. 단점은 VC이 거대(Massive)해진다.
- MVVM : Model & View & ViewModel
    - View가 VC로 봐도 무방하다. 왜냐면 ViewModel에서는 비즈니스적인 로직만 처리하고 VC에 값을 알려주고 VC는 그 값을 받아서 사용하기 때문. VC과 Model은 직접적으로 연관이 없다. ViewModel은 백그라운드스레드에서 로직을 처리하고 VC은 메인 스레드에서 처리해줘야한다.
    - ViewModel은 **Model이 얻어 온 데이터를 View에 맞게 가공/처리하는 역할**을 담당.
    - ViewModel은 Model이 변경되면 자동으로 View도 변경될 수 있도록 **데이터 바인딩**을 한다. (데이터 일관성 유지!) **데이터 바인딩은 뷰와 로직이 따로 나뉘어 있지만, 한 쪽이 변하면 다른 한 쪽도 함께 변하는 것.**

**Comment by Glsme** [comment]
# MVVM
- 기존 MVC 패턴 (Model, View, Controller) 에서 확장되어 나온 디자인 패턴(Model, View, ViewModel) 이다.
- MVC 패턴 중 Controller에서 UI 관련 작업 + 비지니스 로직 중 비지니스 로직만을 따로 관리하기 위하여 나온 패턴이다.
- 비지니스 로직만을 관리하는 객체 ViewModel을 추가로 만들어 관리한다.
- 보통 View 객체는 View와 ViewController를 묶어서 생각한다.

![image](https://user-images.githubusercontent.com/88874280/212539698-b7f79c53-431b-477b-95a7-1e5e590d9da3.png)

**Comment by LeeJoobang** [comment]
### MVC

#### 역할

- model: 어플리케이션에서 사용되는 데이터와 데이터를 처리하는 부분
- view:  사용자에게 보여지는 ui 부분
- controller: 사용자의 입력을 받고 처리하는 부분

#### 특징

- controller는 여러개의 view를 선택할 수 있는 1:n의 구조
- controller는 view계층, model 계층을 모두 소유하며, view가 유저 상호작용을 전달하는 방식도 모두 delegation 방식을 통해 controller가 담당하고 있음.

### MVVM

#### 역할

- model: 어플리케이션에서 사용되는 데이터와 데이터를 처리하는 부분
- view:  사용자에게 보여지는 ui 부분
- view model: 앱의 핵심적인 비즈니스 로직을 담고 있는 코드 계층이다. MVC 패턴의 controller 와 비슷한 역할을 한다. model의 변경사항을 view에게 notification을 보여줌.

#### 특징

- Mvvm 패턴은 command 패턴과 data binding 두가지 패턴을 사용해 구현되었음.
- View model과 view는 1:n 의 관계
- 각 계층의 모듈화가 가능하여 테스트가 용이해짐.

**Comment by heydoy** [comment]
## MVC 
Model, View, Controller
![image](https://user-images.githubusercontent.com/51395335/215504377-8f4c6d78-1d4c-4739-bbab-4fa698bcc551.png)
1. Business logic: 모든 비즈니스 로직이 컨트롤러에 쓰여 있고, 그 때문에 컨트롤러가 거대해져서 관리하기가 어려울 수 있음.  
2. Communication: 뷰와 모델이 컨트롤러를 통해 상호작용함


## MVVM
Model, View, Controller, ViewModel
* MVVM에서는 뷰와 모델 사이에 의사소통만 책임짐 
![image](https://user-images.githubusercontent.com/51395335/215504662-4f39fa15-6e9e-4e6e-a5a4-486354dac20c.png)
비즈니스 로직을 도메인 로직과 어플리케이션 로직으로 분리.
도메인과 관련된 로직을 모델 클래스에, 어플리케이션 로직이 쓰여지는 어플리케이션 서비스 레이어 클래스는  뷰모델과 통신. 
![image](https://user-images.githubusercontent.com/51395335/215505291-4b21d9f4-b282-468b-98d3-d39ca911812e.png)

1. 뷰 모델은 하나 이상의 어플리케이션 서비스 레이어 (API, 네트워크, 데이터베이스 매니저 레이어), 데이터 모델 오브젝트, 뷰 레이어와 통신
2. 모델 오브젝트는 도메인 로직만 담당. 
3. 뷰는 사용자와 상호작용하고, 사용자 앣션을 뷰모델에 보내고 그 결과를 사용자가 이해할 수 있는 포맷으로 전달. 
4. 어플리케이션 레이어는 어플리케이션 로직 담당. 서로와도 연락함. 


* 참고: https://medium.com/swiftcommmunity/understanding-of-implementation-differences-between-mvc-and-mvvm-design-patterns-6c81192f0309

**Comment by wodyddml2** [comment]
## MVC
Model-View-Controller

Controller가 View와 Model을 모두 소유하는 형태 
MVC는 ViewController가 대부분의 역할을 맡아 Massive ViewController라고도 불린다.

## MVVM
Model-View-ViewModel

View가 ViewModel을 소유하고 ViewModel이 Model을 소유하는 형태
MVVM은 ViewModel을 통해 Controller의 역할 중 비즈니스 로직을 분리해서 처리하고 View는 화면 구성만 할 수 있어 Controller의 역할을 줄이고 코드량을 줄일 수 있다.


## 차이점
예를 들자면,
MVC 패턴은 유저와 상호작용 시 View에서 Controller에게 알리고 Controller가 모두 처리한다면
MVVM은 ViewModel이 로직만 가지고 있고 View에서 처리할지 결정만 한다.
