### ISSUE TITLE
Enum의 caselterable과 연관 값(Associated Values)

### ISSUE THREAD

**Issue by Glsme** [NOW-ON/iOS-Interview-Preparation#15]
### 🗓️ 마감일 
2023.01.29

### 💁 참여자

- [x] 김도이
- [x] 윤여진
- [x] 홍석준
- [x] 이주영
- [x] 이재용

⚠️ 마지막으로 답변 단 사람이 이슈 close 하고 리드미에 항목 업데이트 해주세요.

**Comment by Yun-YeoJin** [comment]
### Associated Values(연관값)
- 원래 모든 case가 동일한 형식으로 Raw Value를 가져야 하고, case 각 값은 미리 지정된 한 가지 값만 가질 수 있음!
- 따라서 이를 보완해서 사용할 수 있는 것이 바로 연관값이다.
- case 옆에 튜플 형태로 원하는 Type을 명시함으로써 만들 수 있다. 
![image](https://user-images.githubusercontent.com/106153549/215324837-d00d2131-777e-45c0-9330-baa447146ac3.png)

### CaseIterable 
- CaseIterable Protocol 을 채택한 타입을 사용할 때, allCases 라는 프로퍼티를 사용해서 열거형 타입의 모든 case 컬렉션에 접근할 수 있다.
- 즉, 연관 값이 없는 열거형에서 보통 CaseIterable을 채택해서 사용할 수 있고, 열거형의 case들의 컬렉션에 접근하기 위해서는 allCases 라는 프로퍼티를 통해서 접근할 수 있다.

**Comment by Glsme** [comment]
# caselterable
- Enum 타입을 배열과 같이 순회할 수 있게 해주는 Protocol이다.

# Associated Values
- 원시값의 한계를 보완하기 위해 나온 개념이다.
- 튜플 형태로 사용한다.

**Comment by LeeJoobang** [comment]
### CaseIterable

- enum 열거형의 값들을 배열 컬렉션과 같이 순회할 수 있도록 해주는 프로토콜
- 모든 case 값들에 대한 컬렉션을 제공하는 타입

```swift
enum CompassDirection: CaseIterable {
  case north, south, east, west
}

let caseList = CompassDirection.allcases.map { $0 }.joined(separater: ", ")
pritn(caseList)
//north, south, east, west
```



### Associated Value

- 각 케이스별 관련 있는 값을 가질 수 있음.

```swift
enum Event {
  case homeScreenView
  case productSelect(index: Int)
  case productScreenView(product: Product)
}
```

**Comment by heydoy** [comment]
## CaseIterable
모든 콜렉션의 값을 제공하는 타입 

```swift
protocol CaseIterable
```
CaseIterable 프로토콜을 준수하는 타입은 일반적으로 연관값 없이도 순회하게 해준다. CaseIterable 타입을 사용하면 `allCases` 프로퍼티를 이용하여 콜렉션의 모든 타입의 케이스에 접근할 수 있다. 


* 참고: https://developer.apple.com/documentation/swift/caseiterable

## Enum's Associated Value
열거형도 각 케이스에 연관값을 저장할 수 있다. 추가적인 정보를 저장함으로써, 좀더 의미있는 데이터를 표현할 수 있다. 


```
enum Barcode {
    case upc(Int, Int, Int, Int)
    case qrCode(String)
}
````

* 참고: https://www.hackingwithswift.com/sixty/2/9/enum-associated-values
* 참고: https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html

**Comment by wodyddml2** [comment]
## caselterable

- Enum 타입을 배열과 같이 순회할 수 있게 해주는 Protocol
- allCases 프로퍼티를 이용하여 콜렉션의 모든 타입의 케이스에 접근 가능

## Associated Values

- 모든 case가 동일한 형식으로 Raw Value를 가져야 하는 원시값의 한계를 보완하기 위해 나온 개념
- 튜플 형태로 Type 명시
