### ISSUE TITLE
Intinalizer & Convenience init

### ISSUE THREAD

**Issue by Glsme** [NOW-ON/iOS-Interview-Preparation#5]
2022.12.26 (월) 모임 전까지 작성해주세요.

- [x] 김도이
- [x] 윤여진
- [x] 홍석준
- [x] 이주영
- [x] 이재용

**Comment by Yun-YeoJin** [comment]
* 초기화는 Class, Struct, Enum 인스턴스를 사용하기 위한 준비 작업, 각 저장 프로퍼티의 초기 값을 설정. 
* 특정 타입의 인스턴스를 생성, 파라미터가 없는 init() 키워드를 사용.
* 옵셔널 타입은 init()이 없어도 된다. -> 옵셔널 타입 프로퍼티는 인스턴스가 만들어질 때, nil로 초기화가 된다.

**Comment by heydoy** [comment]
## Initializers
생성자는 특정 타입의 새 인스턴스를 생성할 때 호출됨. 가장 기본적인 형태로는 파라미터가 없는 인스턴스 메서드와 같음. 

```swift
init() {
 // 여기서 초기화를 실행 
}
```


## Designated and Convenience initializers
```swift
init(파라미터) {
   // 구문
}
```

```swift
convenience init(파라미터) {
   // 구문
} 
```

## 클래스타입의 이니셜라이저 위임 규칙

1. 지정 이니셜라이저는 반드시 바로 위 수퍼 클래스의 지정 이니셜라이저를 호출해야함. 
2. Convenience 이니셜라이저는 같은 클래스의 다른 이니셜라이저를 호출해야함. 
3. Convenience 이니셜라이저는 반드시 지정 이니셜라이저를 온전히 호출해야함. 

<img width="456" alt="image" src="https://user-images.githubusercontent.com/51395335/209522582-6971b6f6-7ebc-4a03-8cdb-fb8df68309ed.png">


* 참고: https://docs.swift.org/swift-book/LanguageGuide/Initialization.html

**Comment by wodyddml2** [comment]
initializer은 특정 타입의 새로운 인스턴스를 만들기 위해 호출되며
기본 형태는 인자 없는 인스턴스 메서드와 유사한 형식으로 init 키워드를 사용한다.

Convenience init은 init을 보조하는 역할
같은 클래스에서 반드시 Designated init을 호출해야하한다. (init은 모든 멤버들을 초기화가 보장되므로)

**Comment by Glsme** [comment]
`initializer`는 모든 저장 속성 초기화를 통한 인스턴스를 생성하는 것이다.
- 오버로딩을 지원한다. 따라서 다양한 파라미터 조합으로 생성자를 여러개 구현이 가능하다.

`convenience init`은 지정 생성자보다 더 적은 개수의 파라미터로 보다 편리하게 생성하기 위한 생성자이다.
- 초기화 과정을 간편하게 제공하기 위함이다.
- 편의생성자의 경우 서브클래스에서 재정의를 못한다. (하위 클래스에서 호출불가가 원칙이다.)
- 구조체(열거형)의 경우, `convenience` 키워드를 붙이지 않아도 다른 생성자를 호출이 가능하다.

**Comment by LeeJoobang** [comment]
initializer
: swift의 초기화 이니셜라이즈이다. 모든 프로퍼티가 초기화 될 수 있도록 한다.
convenience init
: 보조 이니셜 라이즈다. 위의 initializer를 돕는 보조적인 열할을 한다고 볼 수 있다.
: 구체적으로 이미 초기화된 프로퍼티의 값의 전부가 아닌 일부를 기본값으로 지정해 놓는 것이다.
