### ISSUE TITLE
앱의 생명주기

### ISSUE THREAD

**Issue by Glsme** [NOW-ON/iOS-Interview-Preparation#7]
### 🗓️ 마감일 
2023.01.15

### 💁 참여자

- [x] 김도이
- [x] 윤여진
- [x] 홍석준
- [x] 이주영
- [x] 이재용

⚠️ 마지막으로 답변 단 사람이 이슈 close 하고 리드미에 항목 업데이트 해주세요.

**Comment by Yun-YeoJin** [comment]
<img width="300" alt="스크린샷 2022-12-26 오후 4 18 22" src="https://user-images.githubusercontent.com/106153549/209517084-94f291f2-7b06-416b-9538-979840a09dd1.png">

- 앱의 실행/종료 및 앱이 포그라운드/백그라운드 상태에 있을 때, 시스템이 발생시키는 이벤트에 의해 앱의 상태가 전환되는 일련의 과정
## 앱 실행시 발생
1. UIApplication 객체 생성
2. @Main 어노테이션이 있는 클래스를 찾아 AppDelegate 객체 생성
3. Main Run Loop 실행 (유저의 액션을 받는 루프)

## 앱 상태 5가지
1. Not running : 앱이 실행되지 않았거나, 완전히 종료되어 동작하지 않는 상태
2. Inactive(Foreground) : 앱이 실행되면서 foreground에 진입, 어떠한 이벤트도 받지 않는 상태 (잠깐 머무는 단계)
3. active(Foreground) : 앱이 실행중, 이벤트를 받고 있는 상태
4. Background : 다른 앱으로 전환 or 홈버튼을 눌러 밖에 있는 상태 -> 일정 시간이 지나면 Suspended 상태가 됨
5. Suspended : 앱이 Background에 있지만, 아무 코드도 실행하지 않은 상태, 메모리 상에 올라가있지만, 배터리는 사용되지 않음. 메모리 부족현상 발생시 이 상태의 앱은 메모리에서 없어질 수 있다.

## AppDelegate 객체 메서드
1. application(_:willFinishLaunchingWithOptions) : 필요한 주요 객체 생성, 앱 실행 준비가 끝나기 직전 호출
2. applicationDidFinishLaunching(_:) : 모든 준비가 끝난 후 화면이 사용자에게 보여지기 직전에 호출 (주로 초기화 코드 작성)
3. applicationWillTerminate(_:) : 앱이 종료되기 직전에 호출
4. sceneWillEnterForeground(_:) : 앱이 백그라운드나 not running에서 foreground로 들어가기 직전에 호출
5. sceneWillResignActive(_:) : 홈바를 쓸어 올렸을 경우 ( 버튼이면 두 번 눌렀을 경우 )
6. sceneDidBecomeActive(_:) : 앱이 비활성화 -> 활성화로 진입하고 난 직후 호출 (앱이 실제로 사용되기 전 준비할 수 있는 코드 작성)
7. sceneDidEnterBackground(_:) : 앱이 백그라운드로 들어갔을 때 호출, 중요한 데이터를 저장하는 등 종료하기 전 필요한 작업

**Comment by wodyddml2** [comment]
앱의 실행 / 종료 및 Foreground / Background의 상태에 있을 때, 시스템이 발생시키는 event로 인해 App의 상태가 전환되는 일련의 과정

→ UIKit이 main 함수를 다루는 과정에서 
→ UIApplicationMain 함수를 실행 
→ 이를 통해 UIApplication 객체 생성 
→ @UIApplicationMain 또는 @Main 어노테이션이 있는 클래스를 찾아 AppDelegate 객체 생성
→ Main Event Loop 실행 (touch, text input 등 사용자 액션) 

### Main Run Loop란?
유저가 일으키는 이벤트들을 처리하는 프로세스
View와 관련된 이벤트나 View의 업데이트에 활용하기에 Main thread에서 실행

### 앱의 상태 5가지
<img width="545" alt="스크린샷 2023-01-11 오후 5 31 58" src="https://user-images.githubusercontent.com/83345066/212537613-2bbaa398-bb87-46df-902c-776f11479385.png">

**Comment by Glsme** [comment]
| 사이클 | 설명 |
|:--:|:--:|
| Not Running | 앱이 아직 실행되지 않았거나, 완전히 종료되어 동작하지 않는 상태 |
| Inactive | 앱이 실행중이지만 사용자로부터 event를 받을 수 없는 상태 |
| Active | 앱이 실행중이고, 사용자 event를 받아서 상호작용 할 수 있느 상태 |
| Background | 화면애 앱이 보지인 않지만 코드가 실행되고 있는 상태 |
| Suspended | 앱을 다시 실행했을 때 최근 작업을 빠르게 로드하기 위해 메모리에 관련 데이터만 저장되어있는 상태 |

**Comment by heydoy** [comment]
## iOS 12 이전 (앱 기반 생명주기)
`UIApplicationDelegate`객체가 앱의 생명주기 이벤트에 반응

![image](https://user-images.githubusercontent.com/51395335/212545839-e36226b2-cd20-49e2-b284-693f17db8412.png)

iOS 12까지는 앱이 씬을 지원하지 않음. UIKit이 모든 생명주기 이벤트를 `UIApplicationDelegate`객체에 전달. 앱델리게이트는 화면에 보여지는 별개의 스크린까지 포함하여 모든 앱의 윈도우를 관리. 그 결과로 앱의 상태 변화는 앱의 전체적인 UI에 영향을 끼침. 

1. 실행되면 앱의 데이터 구조와 UI를 초기화함
2. activate 되면 UI 구성을 끝내고 사용자와 상호작용할 준비를 함 
3. deactivate 되면 데이터를 저장하고 앱의 동작을 정지
4. 백그라운드 상태에 진입하면 중요한 작업을 끝내고 최대한 많은 메모리를 해제하고 앱의 스냅샷을 준비
5. terminattion(종료)되면 모든 작업을 즉시 중단하고 공유자원을 모두 해제 

## iOS 13 이후 (씬 기반 생명주기)
`UISceneDelegate`객체가 씬 기반 앱의 생명주기 이벤트에 반응 
앱이 씬을 지원할 경우 UIKit이 별개의 생명주기 이벤트를 전달. 

![image](https://user-images.githubusercontent.com/51395335/212546326-1a1deb04-04f4-40d8-8e9c-1397fa23c087.png)

1. UIKit이 앱의 씬에 연결되면 씬의 처음 UI를 구성하고 씬에 필요한 데이터를 로드
6. foreground-active 상태로 전환될 때 UI를 구성하고 사용자와 인터랙트할 준비를 함. 
7. foreground-active 상태를 떠날 때 데이터를 저장하고 앱의 동작을 멈춤 
8. background 상태에 진입하면 중요한 태스크를 끝내고 최대한 많은 메모리를 해제하고 앱의 스냅샷을 준비
9. 씬 연결이 끊기면 씬과 관련된 공유자원을 청소함
10. 씬과 관련된 이벤트에서는 `UIApplicationDelegate` 객체를 사용하여 앱 실행에 반응해야한다. 


* 참고링크: https://developer.apple.com/documentation/uikit/app_and_environment/managing_your_app_s_life_cycle

**Comment by LeeJoobang** [comment]
- 앱의 생명주기란? 앱의 실행부터 종료까지의 주기를 말하며, 앱이 foreground, background에 있을 때 시스템 알림에 응답하고, 기타 중요한 시스템 관련 이벤트를 처리하는 단계를 말한다.
- 왜 중요한가? cpu는 한정된 리소스로 사용자에게 여러가지 기능을 제공한다. ios 모바일 환경 또한 하나의 cpu가 제한된 메모리와 시간을 여러 앱에 할당하게 된다. 이때 가장 높은 순위를 갖는 앱은 한 시점에 사용자에게 보여지는 앱이다. 그런데 여러 앱을 번갈아가며 사용할 때, 잠시 다른 앱을 사용한다고 해서 이전의 모든 데이터가 초기화 되거나 다시 로그인을 해야 하는 등의 흐름은 사용성을 매우 해침, 이를 이해하는 게 필요하다.
- 앱의 main run loop는 모든 사용자가 발생시키는 이벤트에 따라 처리된다. 이벤트 발생했을 때, uikit에 의해 설정된 port를 통해 내부의  event queue에 이벤트를 담아 놓고, 담겨있는 이벤트를 main run loop에서 하나씩 실핸한다.
- main run loop는 앱의 main thread를 실행(앱을 돌면서 모든 이벤트를 처리한다) 이러한 것들은 앱 사용자가 발생하는 이벤트를 순차적으로 처리하기 위해 사용된다.
- 앱 state
  - 5가지
  - not running
  - forground - inactive: inactive - app이 실행중이지만, 사용자로부터 event를 받을 수 없는 상태, multitasking window로 진입하거나, app 실행 중 전화, 알림 등에 의해 app을 사용할 수 없게 되는 경우 이상태로 진입
  - foreground - active: active는 app이 실제 실행중이고, 사용자 event를 받아서 상호작용할 수 있는 상태, 바로 active 되지 않고, inactive 상태를 거쳐 active상태가 된다.
  - background - running: background 는 홈화면으로 나가거나 다른 app으로 전환되어 현재 app이 실질적으로 동작하지 않은 상태, music앱을 닫아도 재생한 음악이 계속 실행되는 경우, 사용자가 앱을 사용하지 않는 동안 서버와 데이터를 동기화 하거나, 타이머가 실행되어야 하는 등의 작업을 이상태에서 할 수 있습니다.
  - background - suspended: suspended는 app을 다시 실행했을 때, 최근 작업을 빠르게 로드하기 위해 메모리에 관련 데이터만 저장되어 있는 상태, app이 background 상태에 진입했을 때, 다른 작업을 하지 않으면 suspended 상태로 진입하게 된다. suspended상태의 app들은 ios메모리가 부족해지면 가장 먼저 메모리에서 해제됨. 따라서 app을 종료시킨 적이 없더라도, app을 다시 실행하려고 하면 처음부터 다시 실행됨.
