### ISSUE TITLE
Collection Type의 종류와 특징

### ISSUE THREAD

**Issue by Glsme** [NOW-ON/iOS-Interview-Preparation#8]
### 🗓️ 마감일 
2023.01.15

### 💁 참여자

- [x] 김도이
- [x] 윤여진
- [x] 홍석준
- [x] 이주영
- [x] 이재용

⚠️ 마지막으로 답변 단 사람이 이슈 close 하고 리드미에 항목 업데이트 해주세요.

**Comment by Yun-YeoJin** [comment]
Array, Set, Dictionary 세 가지가 있다.
var(변수)로 할당하면 변경이 가능하지만, let으로 할당하면 변경이 불가능하다.
1. **Array(배열)** : [Element] 형태, .count를 이용해 갯수 확인 가능, .append나 .insert를 통해 원소 추가 가능, for_in loop 순회 가능
2. **Set** : Set 형태로 저장되기 위해서는 타입이 hashable(String, Int, Double, Bool)이어야 한다. Set<String> 식으로 선언 가능
 -> intersection(교집합), symmetricDifference(차집합), union(합집합), subtracting(여집합)
3. **Dictionary(딕셔너리)** : [Key, Value] 형태, [Int, String] 형태로 선언 가능

**Comment by wodyddml2** [comment]
- Array
    - 정렬된 값들의 컬렉션
- Set
    - Hashable한 값들을 가지고 있는 비정렬 컬렉션
- Dictionary
    - 중복되지 않은 Key-Value 형태의 값을 가지는 컬렉션

**Comment by Glsme** [comment]
### Array
- 데이터를 순서대로 저장하는 컬렉션
### Dictionary
- 데이터를 키와 값으로 하나의 쌍을 만들어 관리하는 순서가 없는 컬렉션
### Set
- 중복된 값이 없고 순서가 없는 컬렉션

**Comment by heydoy** [comment]
## 콜렉션 타입의 종류 및 특징

![image](https://user-images.githubusercontent.com/51395335/212546357-4f3b5b38-1cf4-461b-a566-49a2de80f009.png)

> Swift 의 이런 타입들은 모두 `Generic Collection`
모든 콜렉션 타임은 Iteratable 하다. for-in 반복문으로 순회가 가능 

### 배열(Array)
```swift
var intArray: [Int] = [1, 2, 3]
var threeInt = Array(repeating: 0, count: 3)

var addedArray = intArray + threeInt
```
- 순서가 있는 콜렉션 

> Swift의 배열은 `Foundation`의 `NSArray` 클래스와 연결됨 

### 세트(Set)
```swift
var charSet = Set<Characters>()
var strSet: Set<String> = ["hello", "swift"]

```
- 순서가 없는 콜렉션
- 고유한 값만 저장 
- Hashable : 해시값을 제공할 수 있어야함 
- 두 세트간에 집합연산이 가능 (합집합, 교집합, 차집합, 부분집합...)

![image](https://user-images.githubusercontent.com/51395335/212546748-02794386-7f0c-4d8c-b072-bb9e9de5df68.png)
![image](https://user-images.githubusercontent.com/51395335/212546769-ea16bf8b-a7ca-4d64-8f78-3681e4e11bd0.png)


### 딕셔너리(Dictionary) 
```swift
var cats: [String: Int] = ["코숏": 3, "아메숏": 2] 

``` 
- 순서가 없는 콜렉션
- 키-밸류 쌍으로 저장됨 
- 고유한 값으로 저장됨 


* 참고링크: https://docs.swift.org/swift-book/LanguageGuide/CollectionTypes.html

**Comment by LeeJoobang** [comment]
Collection Type의 종류와 특징 설명
- 배열 - 같은 타입의 데이터를 순서있게 보관
  - 배열은 앞서 말한 것과 같이 같은 타입의 데이터들을 순서있게 보관하는 통입니다. 즉, 통에 포함된 아이템들의 순서를 알아야 하거나 혹은 순서를 알면 유용한 경우에 사용합니다.\
  - 배열은 항상 저장된 순서대로 정렬되어 있음 (Ordered Collection)
    \- 배열에 저장하는 데이터의 타입은 항상 동일해야 함 (Single Type)
    \- 값은 중복되어 저장할 수 있음
    \- 요소에 접근할 때는 인덱스를 사용 (0-based Index)
    \- 중간 요소가 삭제되는 경우 뒤에 요소들이 앞으로 이동하며 자동으로 인덱스 재정렬
    \- 배열 중간에 요소를 추가하는 경우 오버헤드가 발생할 수 있으니 가능하면 맨 뒤에 삽입
- 세트 - 같은 타입의 데이터 순서 없게 보관
  - \- 정렬 순서보다 검색 속도가 중요한 경우 배열 대신 사용 (Hashing 알고리즘 사용)
    \- 정렬되지 않으며 인덱스를 사용하지도 않음 (Unordered Collection)
    \- 동일한 형식의 요소를 저장 (Single Type)
    \- 동일한 값을 하나만 저장, 중복 불가 (Single Unique Value)
- 딕셔너리 - 키와 값을 한쌍으로 순서없게 보관
  - Dictionary 란, 사전과 유사한 형태로 데이터를 저장하는 collection 으로 key-value 쌍을 저장합니다. 이때 key 는 해당 collection 에서 유일한 값이어야 합니다. 특징은 다음과 같습니다
    \- 정렬되지 않은 상태로 저장 (Unordered Collection)
    \- 한 dictionary 에 저장되는 데이터 타입은 모두 동일 (Single Type)
